[package]
name = "test-project"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.0"
tokio = { version = "1.0.0", features = ["full"] }
web3 = "0.19.0"
anyhow = "1.0.95"

[dev-dependencies]
mockall = "0.11.0"

[build-dependencies]
cc = "1.0.0"
